        <!-- Top content -->
        <div class="top-content">
        	
            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-2 text">
                            <h1><strong>Loc</strong><moto> motoboy</moto></h1>
                            <div class="description">
                            	<p>
	                            	A maneira mais fácil e segura de chamar um motoboy.
                            	</p>
                            </div>
                        </div>
                        
                    </div>
                  
                    <div class="row">
                     <div class="meumenu">
                    <div class="row">
                    	<ul class="nav nav-pills nav-stacked">
                        	<div class="col-sm-16 col-sm-offset-3 social-login">
                           	<div class="social-login-buttons">
                           	<li><a class="btn btn-link-1 btn-link-1-login" href="user/login">Faça seu login.</a></li>
	                        <li><a class="btn btn-link-1 btn-link-1-cadastro" href="user/cadastrar">Cadastro gratis</a></li>
	                        <li><a class="btn btn-link-1 btn-link-1-comofunciona" href="#">Como funciona</a></li>
	                        
	                    </div>
	                    </div>
	                    </ul>
                       
					</div>
                    </div>
                       
                        
                    </div>
              
                </div>
            </div>
            
        </div>
 